seed = 0
function = "bin.xgboost_.main"
n_trials = 200
timeout = "__null__"

[sampler]
n_startup_trials = 20

[space]
seed = 0

[space.data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/classif-cat-medium-0-electricity"
cat_policy = "one-hot"
y_policy = "__null__"

[space.model]
booster = "gbtree"
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_bytree = 0.807624868932365
gamma = 0
lambda = 0.0
learning_rate = 0.017353011148469853
max_depth = 11
min_child_weight = 0.008373769011810068
subsample = 0.9180711882729445

[space.fit]
early_stopping_rounds = 200
verbose = true
