seed = 0
function = "bin.ffn.main"
n_trials = 100
timeout = "__null__"

[sampler]

[space]
seed = 0
num_embeddings = "__null__"
batch_size = 256
patience = 16
n_epochs = inf

[space.data]
seed = 0
cache = true
path = ":data/classif-num-large-0-jannis"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[space.model]
type = "MLP"
n_blocks = 6
d_layer = 623
dropout = 0.3969868740593321
activation = "ReLU"

[space.optimizer]
type = "AdamW"
lr = 0.0009958021465946508
weight_decay = 0.0
