seed = 0
function = "bin.ffn.main"
n_trials = 100
timeout = "__null__"

[sampler]

[space]
seed = 0
batch_size = 256
patience = 16
n_epochs = inf

[space.data]
seed = 0
cache = true
path = ":data/classif-cat-medium-0-electricity"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "__null__"

[space.optimizer]
type = "AdamW"
lr = 0.00047450038619567243
weight_decay = 9.026081982383072e-06

[space.model.backbone]
type = "MLP"
n_blocks = 6
d_layer = 708
dropout = 0.0
activation = "ReLU"

[space.model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 29
frequency_scale = 0.010985777700535139
d_embedding = 64
lite = true
