seed = 0
function = "bin.ffn.main"
n_trials = 100
timeout = "__null__"

[sampler]

[space]
seed = 0
batch_size = 128
patience = 16
n_epochs = inf

[space.data]
seed = 0
cache = true
path = ":data/classif-num-medium-0-bank-marketing"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[space.optimizer]
type = "AdamW"
lr = 0.00018096794357793283
weight_decay = 0.0

[space.model.backbone]
type = "MLP"
n_blocks = 5
d_layer = 686
dropout = 0.4914330566596081
activation = "ReLU"

[space.model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 42
frequency_scale = 0.5143199671670529
d_embedding = 42
lite = true
