seed = 0
function = "bin.xgboost_.main"
n_trials = 200
timeout = "__null__"

[sampler]
n_startup_trials = 20

[space]
seed = 0

[space.data]
seed = 0
num_policy = "__null__"
cache = true
path = ":data/classif-num-medium-0-MagicTelescope"
cat_policy = "__null__"
y_policy = "__null__"

[space.model]
booster = "gbtree"
n_estimators = 4000
n_jobs = 1
tree_method = "gpu_hist"
use_label_encoder = false
colsample_bytree = 0.9089283982258239
gamma = 0.08791127313282383
lambda = 0.0
learning_rate = 0.09038947788589377
max_depth = 5
min_child_weight = 0.030822510514354678
subsample = 0.8949316909099935

[space.fit]
early_stopping_rounds = 200
verbose = true
